package scripts.fc.framework.equipment;

import org.tribot.api2007.Equipment.SLOTS;
import org.tribot.api2007.Skills.SKILLS;

import scripts.fc.framework.equipment.requirement.EquipLvlReq;
import scripts.fc.framework.equipment.requirement.SettingReq;
import scripts.fc.framework.equipment.requirement.WieldEquipmentRequirement;

public enum EquipData {
	
	//MELEE HELMETS
	BRONZE_MED_HELM(1139, CombatType.MELEE, SLOTS.HELMET),
	BRONZE_FULL_HELM(1155, CombatType.MELEE, SLOTS.HELMET),
	IRON_MED_HELM(1137, CombatType.MELEE, SLOTS.HELMET),
	IRON_FULL_HELM(1153, CombatType.MELEE, SLOTS.HELMET),
	STEEL_MED_HELM(1141, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 5)),
	STEEL_FULL_HELM(1157, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 5)),
	BLACK_MED_HELM(1151, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 10)),
	BLACK_FULL_HELM(1165, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 10)),
	MITHRIL_MED_HELM(1143, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 20)),
	MITHRIL_FULL_HELM(1159, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 20)),
	ADAMANT_MED_HELM(1145, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 30)),
	ADAMANT_FULL_HELM(1161, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 30)),
	RUNE_MED_HELM(1147, CombatType.MELEE, SLOTS.HELMET, new EquipLvlReq(SKILLS.DEFENCE, 40)),
	RUNE_FULL_HELM(1163, CombatType.MELEE, SLOTS.HELMET, 1, new EquipLvlReq(SKILLS.DEFENCE, 40)),
	
	//MELEE BODIES
	BRONZE_CHAINBODY(1103, CombatType.MELEE, SLOTS.BODY),
	IRON_CHAINBODY(1101, CombatType.MELEE, SLOTS.BODY),
	STEEL_CHAINBODY(1105, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 5)),
	BLACK_CHAINBODY(1107, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 10)),
	MITHRIL_CHAINBODY(1109, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 20)),
	ADAMANT_CHAINBODY(1111, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 30)),
	RUNE_CHAINBODY(1113, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 40)),
	
	BRONZE_PLATEBODY(1117, CombatType.MELEE, SLOTS.BODY),
	IRON_PLATEBODY(1115, CombatType.MELEE, SLOTS.BODY),
	STEEL_PLATEBODY(1119, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 5)),
	BLACK_PLATEBODY(1126, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 10)),
	MITHRIL_PLATEBODY(1121, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 20)),
	ADAMANT_PLATEBODY(1123, CombatType.MELEE, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 30)),
	RUNE_PLATEBODY(1127, CombatType.MELEE, SLOTS.BODY, 1, new EquipLvlReq(SKILLS.DEFENCE, 40), new SettingReq(-1,-1)), //TODO ADD DRAGON SLAYER SETTING
	
	//MELEE LEGS
	BRONZE_PLATESKIRT(1087, CombatType.MELEE, SLOTS.LEGS),
	IRON_PLATESKIRT(1081, CombatType.MELEE, SLOTS.LEGS),
	STEEL_PLATESKIRT(1083, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 5)),
	BLACK_PLATESKIRT(1089, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 10)),
	MITHRIL_PLATESKIRT(1085, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 20)),
	ADAMANT_PLATESKIRT(1091, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 30)),
	RUNE_PLATESKIRT(1093, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 40)),
	
	BRONZE_PLATELEGS(1075, CombatType.MELEE, SLOTS.LEGS),
	IRON_PLATELEGS(1067, CombatType.MELEE, SLOTS.LEGS),
	STEEL_PLATELEGS(1069, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 5)),
	BLACK_PLATELEGS(1077, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 10)),
	MITHRIL_PLATELEGS(1071, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 20)),
	ADAMANT_PLATESLEGS(1073, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 30)),
	RUNE_PLATESLEGS(1079, CombatType.MELEE, SLOTS.LEGS, new EquipLvlReq(SKILLS.DEFENCE, 40)),
	
	//SHIELDS
	
	//MELEE WEAPONS
	BRONZE_DAGGER(1205, CombatType.MELEE, SLOTS.WEAPON),
	IRON_DAGGER(1203, CombatType.MELEE, SLOTS.WEAPON),
	STEEL_DAGGER(1207, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 5)),
	BLACK_DAGGER(1217, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 10)),
	MITHRIL_DAGGER(1209, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 20)),
	ADAMANT_DAGGER(1211, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 30)),
	RUNE_DAGGER(1214, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 40)),
	
	BRONZE_SWORD(1277, CombatType.MELEE, SLOTS.WEAPON),
	IRON_SWORD(1279, CombatType.MELEE, SLOTS.WEAPON),
	STEEL_SWORD(1281, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 5)),
	BLACK_SWORD(1283, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 10)),
	MITHRIL_SWORD(1285, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 20)),
	ADAMANT_SWORD(1287, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 30)),
	RUNE_SWORD(1289, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 40)),
	
	BRONZE_WARHAMMER(1337, CombatType.MELEE, SLOTS.WEAPON),
	IRON_WARHAMMER(1335, CombatType.MELEE, SLOTS.WEAPON),
	STEEL_WARHAMMER(1339, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 5)),
	BLACK_WARHAMMER(1341, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 10)),
	MITHRIL_WARHAMMER(1343, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 20)),
	ADAMANT_WARHAMMER(1345, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 30)),
	RUNE_WARHAMMER(1347, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 40)),
	
	BRONZE_BATTLEAXE(1375, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 1)),
	IRON_BATTLEAXE(1363, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 1)),
	STEEL_BATTLEAXE(1365, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 5)),
	BLACK_BATTLEAXE(1367, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 10)),
	MITHRIL_BATTLEAXE(1369, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 20)),
	ADAMANT_BATTLEAXE(1371, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 30)),
	RUNE_BATTLEAXE(1373, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 40)),
	
	BRONZE_LONGSWORD(1291, CombatType.MELEE, SLOTS.WEAPON),
	IRON_LONGSWORD(1293, CombatType.MELEE, SLOTS.WEAPON),
	STEEL_LONGSWORD(1295, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 5)),
	BLACK_LONGSWORD(1297, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 10)),
	MITHRIL_LONGSWORD(1299, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 20)),
	ADAMANT_LONGSWORD(1301, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 30)),
	RUNE_LONGSWORD(1303, CombatType.MELEE, SLOTS.WEAPON, 1, new EquipLvlReq(SKILLS.ATTACK, 40)),
	
	BRONZE_SCIMITAR(1321, CombatType.MELEE, SLOTS.WEAPON),
	IRON_SCIMITAR(1323, CombatType.MELEE, SLOTS.WEAPON),
	STEEL_SCIMITAR(1325, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 5)),
	BLACK_SCIMITAR(1327, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 10)),
	MITHRIL_SCIMITAR(1329, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 20)),
	ADAMANT_SCIMITAR(1331, CombatType.MELEE, SLOTS.WEAPON, new EquipLvlReq(SKILLS.ATTACK, 30)),
	RUNE_SCIMITAR(1333, CombatType.MELEE, SLOTS.WEAPON, 2, new EquipLvlReq(SKILLS.ATTACK, 40)),
	
	BRONZE_2H(1321, CombatType.MELEE, SLOTS.WEAPON, true),
	IRON_2H(1323, CombatType.MELEE, SLOTS.WEAPON, true),
	STEEL_2H(1325, CombatType.MELEE, SLOTS.WEAPON, true, new EquipLvlReq(SKILLS.ATTACK, 5)),
	BLACK_2H(1327, CombatType.MELEE, SLOTS.WEAPON, true, new EquipLvlReq(SKILLS.ATTACK, 10)),
	MITHRIL_2H(1329, CombatType.MELEE, SLOTS.WEAPON, true, new EquipLvlReq(SKILLS.ATTACK, 20)),
	ADAMANT_2H(1331, CombatType.MELEE, SLOTS.WEAPON, true, new EquipLvlReq(SKILLS.ATTACK, 30)),
	RUNE_2H(1333, CombatType.MELEE, SLOTS.WEAPON, true, new EquipLvlReq(SKILLS.ATTACK, 40)),
	
	//capes
	RED_CAPE(1007, CombatType.MISC, SLOTS.CAPE),
	BLUE_CAPE(1021, CombatType.MISC, SLOTS.CAPE),
	GREEN_CAPE(1027, CombatType.MISC, SLOTS.CAPE),
	BLACK_CAPE(1019, CombatType.MISC, SLOTS.CAPE),
	ORANGE_CAPE(1031, CombatType.MISC, SLOTS.CAPE),
	PURPLE_CAPE(1029, CombatType.MISC, SLOTS.CAPE),
	
	//RANGED ARMOR
	LEATHER_COWL(1167, CombatType.RANGED, SLOTS.HELMET),
	LEATHER_VAMBRACES(1063, CombatType.RANGED, SLOTS.GLOVES),
	LEATHER_CHAPS(1095, CombatType.RANGED, SLOTS.LEGS),
	LEATHER_BODY(1129, CombatType.RANGED, SLOTS.BODY),
	HARD_LEATHER_BODY(1131, CombatType.RANGED, SLOTS.BODY, new EquipLvlReq(SKILLS.DEFENCE, 10)),
	
	STUDDED_BODY(1133, CombatType.RANGED, SLOTS.BODY, new EquipLvlReq(SKILLS.RANGED, 20), new EquipLvlReq(SKILLS.DEFENCE, 20)),
	STUDDED_CHAPS(1097, CombatType.RANGED, SLOTS.LEGS, new EquipLvlReq(SKILLS.RANGED, 20)),
	COIF(1169, CombatType.RANGED, SLOTS.HELMET, new EquipLvlReq(SKILLS.RANGED, 20)),
	
	GREEN_DHIDE_BODY(1135, CombatType.RANGED, SLOTS.BODY, new EquipLvlReq(SKILLS.RANGED, 40), new EquipLvlReq(SKILLS.DEFENCE, 40)),
	GREEN_DHIDE_CHAPS(1099, CombatType.RANGED, SLOTS.LEGS, new EquipLvlReq(SKILLS.RANGED, 40)),
	GREEN_DHIDE_VAMBRACES(1065, CombatType.RANGED, SLOTS.GLOVES, new EquipLvlReq(SKILLS.RANGED, 40)),
	
	//BOWS
	TRAINING_BOW(9705, CombatType.RANGED, SLOTS.WEAPON, true),
	SHORTBOW(841, CombatType.RANGED, SLOTS.WEAPON, true),
	OAK_SHORTBOW(843, CombatType.RANGED, SLOTS.WEAPON, true, new EquipLvlReq(SKILLS.RANGED, 5)),
	WILLOW_SHORTBOW(849, CombatType.RANGED, SLOTS.WEAPON, true, new EquipLvlReq(SKILLS.RANGED, 20)),
	MAPLE_SHORTBOW(853, CombatType.RANGED, SLOTS.WEAPON, true, new EquipLvlReq(SKILLS.RANGED, 30)),
	
	//ARROWS
	
	;
	
	final int[] IDS;
	final CombatType TYPE;
	final SLOTS SLOT;
	final WieldEquipmentRequirement[] REQUIREMENTS;
	
	boolean is2Handed = false;
	int priority = 0;
	
	EquipData(int id, CombatType type, SLOTS slot, WieldEquipmentRequirement... reqs) {
		IDS = new int[]{id};
		TYPE = type;
		SLOT = slot;
		REQUIREMENTS = reqs;
	}
	
	EquipData(int id, CombatType type, SLOTS slot, int priority, WieldEquipmentRequirement... reqs) {
		this(id, type, slot, reqs);
		this.priority = priority;
	}
	
	EquipData(int id, CombatType type, SLOTS slot, boolean is2H, WieldEquipmentRequirement... reqs) {
		this(id, type, slot, reqs);
		this.is2Handed = is2H;
	}
	
	EquipData(int id, CombatType type, SLOTS slot, boolean is2H, int priority, WieldEquipmentRequirement... reqs) {
		this(id, type, slot, is2H, reqs);
		this.priority = priority;
	}
}
